version: '2.2'
networks:
  internal:
    driver: bridge
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      INITIAL_ROOT_PASSWORD: "%123wordpress"
    expose:
      - 3306
    networks:
      - internal
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 8080:80
    networks:
      - internal
