version: '2.2'
volumes:
  mysql-mnt:
  mysql-data:
  wordpress-data:
networks:
  internal:
    driver: bridge
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - 3306
    networks:
      - internal
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-mnt:/mnt
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 8080:80
    networks:
      - internal
    volumes:
      - wordpress-data:/var/www/html
