version: '2.2'
volumes:
  password-mnt:
  mysql-data:
  wordpress-data:
networks:
  internal:
    driver: bridge
services:
  mysql:
    build:
      context: ./files
      dockerfile: Dockerfile.backend
    expose:
      - 3306
    networks:
      - internal
    volumes:
      - mysql-data:/var/lib/mysql
      - password-mnt:/mnt
  wordpress:
    build:
      context: ./files
      dockerfile: Dockerfile.frontend
    ports:
      - localhost:8080:80
    networks:
      - internal
    volumes:
      - wordpress-data:/var/www/html
      - password-mnt:/mnt
