FROM centos:7

RUN set -ex; \
yum makecache fast; \
yum install -y httpd php php-mysql mariadb; \
curl -L https://wordpress.org/latest.tar.gz | tar -xzC /var/www/html/ --strip-components 1; \
yum clean all; \
rm -rf /tmp/*

EXPOSE 80

CMD /usr/sbin/httpd -DFOREGROUND
